name: Version Check

on:
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version increased
        uses: EndBug/version-check@v1
        with:
          previous-version-command: 'git show origin/${{ github.base_ref }}:package.json | jq -r .version'
          current-version-command: 'jq -r .version package.json'
          require-increase: true
